FROM python:3.10

# requirements for app are installed
COPY ./requirements_gateway.txt /tmp/requirements.txt
RUN pip3 install --upgrade pip
RUN pip install -r /tmp/requirements.txt

# run backend app
WORKDIR /app
EXPOSE 8014
CMD uvicorn app.main:app --host 0.0.0.0 --port 8014 --reload